### ISSUE TITLE
Mezcla natural

### ISSUE THREAD

**Issue by belferster** [justog220/TP-Algoritmo-ZG#4]
Hola chicos cómo están?
Les aviso que probé su código de mezcla natural con solo 20 datos a ordenar y anda, pero por ejemplo con 200 queda en un ciclo infinito mostrando por consola que quedan 2 sublistas ordenadas. Fijense si subieron la última versión por las dudas. Si pueden vuelvan a revisar, pero si sigue sin funcionar nos vemos en la consulta si les parece.

**Comment by justog220** [comment]
Buenas tardes, modificamos el algoritmo y fuimos capaces de ordenar el archivo con esos parametros.
